<?php // MYSQL anbinden für Ticker
error_reporting(E_ALL);
$connect = mysqli_connect("localhost", "root", "root", "notificationData");
// 24 HOURS
$query1 = "SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR Aktuell')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Inforadio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'rbb|24')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Brandenburg Aktuell')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Radio Paloma')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Radio SAW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'hr-INFO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Fritz')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'YOU FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'hr2-kultur')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'hr3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'boerse.ARD')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Kulturradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'radioeins')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'DASDING')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'KaffeeOderTee')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR4 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR4 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'ARDBuffet')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR1 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR1 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'ROCKLAND.fm')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE '1A Webradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Hit Radio N1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Charivari 98.6')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Radio F 94.5')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Pirate Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Gong 97.1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Radio TEDDY')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'WIGLmania')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'BB RADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Kochblogradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Radio Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SCHWARZWALDRADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Retro FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Abendschau') ORDER BY `number` DESC LIMIT 10";
$query2 = "SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR Aktuell')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Inforadio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'rbb|24')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Brandenburg Aktuell')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Radio Paloma')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Radio SAW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'hr-INFO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Fritz')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'YOU FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'hr2-kultur')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'hr3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'boerse.ARD')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Kulturradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'radioeins')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'DASDING')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'KaffeeOderTee')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR4 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR4 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'ARDBuffet')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR1 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SWR1 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'ROCKLAND.fm')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE '1A Webradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Hit Radio N1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Charivari 98.6')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Radio F 94.5')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Pirate Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Gong 97.1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Radio TEDDY')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'WIGLmania')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'BB RADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Kochblogradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Radio Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'SCHWARZWALDRADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Retro FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)) AND (appName LIKE 'Abendschau') ORDER BY `number` DESC LIMIT 10";



// WEEK
$query3 = "SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR Aktuell')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Inforadio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'rbb|24')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Brandenburg Aktuell')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Radio Paloma')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Radio SAW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'hr-INFO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Fritz')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'YOU FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'hr2-kultur')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'hr3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'boerse.ARD')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Kulturradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'radioeins')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'DASDING')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'KaffeeOderTee')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR4 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR4 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'ARDBuffet')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR1 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR1 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'ROCKLAND.fm')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE '1A Webradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Hit Radio N1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Charivari 98.6')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Radio F 94.5')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Pirate Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Gong 97.1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Radio TEDDY')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'WIGLmania')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'BB RADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Kochblogradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Radio Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SCHWARZWALDRADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Retro FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Abendschau') ORDER BY `number` DESC LIMIT 10";
$query4 ="SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR Aktuell')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Inforadio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'rbb|24')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Brandenburg Aktuell')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Radio Paloma')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Radio SAW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'hr-INFO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR3')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Fritz')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'YOU FM')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'hr2-kultur')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'hr3')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'boerse.ARD')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Kulturradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'radioeins')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'DASDING')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'KaffeeOderTee')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR4 BW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR4 RP')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'ARDBuffet')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR1 RP')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SWR1 BW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'ROCKLAND.fm')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE '1A Webradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Hit Radio N1')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Charivari 98.6')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Radio F 94.5')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Pirate Gong')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Gong 97.1')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Radio TEDDY')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'WIGLmania')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'BB RADIO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Kochblogradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Radio Gong')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'SCHWARZWALDRADIO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Retro FM')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 7 DAY)) AND (appName LIKE 'Abendschau') ORDER BY `number` DESC LIMIT 10";
// MONTH
$query5 = "SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR Aktuell')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Inforadio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'rbb|24')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Brandenburg Aktuell')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Radio Paloma')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Radio SAW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'hr-INFO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Fritz')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'YOU FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'hr2-kultur')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'hr3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'boerse.ARD')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Kulturradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'radioeins')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'DASDING')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'KaffeeOderTee')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR4 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR4 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'ARDBuffet')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR1 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR1 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'ROCKLAND.fm')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE '1A Webradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Hit Radio N1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Charivari 98.6')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Radio F 94.5')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Pirate Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Gong 97.1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Radio TEDDY')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'WIGLmania')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'BB RADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Kochblogradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Radio Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SCHWARZWALDRADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Retro FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Abendschau') ORDER BY `number` DESC LIMIT 10";
$query6 = "SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR Aktuell')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Inforadio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'rbb|24')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Brandenburg Aktuell')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Radio Paloma')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Radio SAW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'hr-INFO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR3')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Fritz')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'YOU FM')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'hr2-kultur')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'hr3')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'boerse.ARD')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Kulturradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'radioeins')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'DASDING')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'KaffeeOderTee')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR4 BW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR4 RP')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'ARDBuffet')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR1 RP')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SWR1 BW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'ROCKLAND.fm')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE '1A Webradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Hit Radio N1')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Charivari 98.6')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Radio F 94.5')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Pirate Gong')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Gong 97.1')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Radio TEDDY')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'WIGLmania')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'BB RADIO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Kochblogradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Radio Gong')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'SCHWARZWALDRADIO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Retro FM')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 30 DAY)) AND (appName LIKE 'Abendschau') ORDER BY `number` DESC LIMIT 10";
// YEAR
$query7 = "SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR Aktuell')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Inforadio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'rbb|24')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Brandenburg Aktuell')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Radio Paloma')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Radio SAW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'hr-INFO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Fritz')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'YOU FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'hr2-kultur')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'hr3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'boerse.ARD')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Kulturradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'radioeins')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'DASDING')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'KaffeeOderTee')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR4 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR4 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'ARDBuffet')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR1 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR1 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'ROCKLAND.fm')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE '1A Webradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Hit Radio N1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Charivari 98.6')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Radio F 94.5')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Pirate Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Gong 97.1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Radio TEDDY')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'WIGLmania')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'BB RADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Kochblogradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Radio Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SCHWARZWALDRADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Retro FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Abendschau') ORDER BY `number` DESC LIMIT 10";
$query8 = "SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR Aktuell')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Inforadio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'rbb|24')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Brandenburg Aktuell')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Radio Paloma')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Radio SAW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'hr-INFO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR3')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Fritz')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'YOU FM')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'hr2-kultur')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'hr3')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'boerse.ARD')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Kulturradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'radioeins')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'DASDING')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'KaffeeOderTee')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR4 BW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR4 RP')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'ARDBuffet')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR1 RP')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SWR1 BW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'ROCKLAND.fm')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE '1A Webradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Hit Radio N1')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Charivari 98.6')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Radio F 94.5')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Pirate Gong')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Gong 97.1')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Radio TEDDY')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'WIGLmania')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'BB RADIO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Kochblogradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Radio Gong')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'SCHWARZWALDRADIO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Retro FM')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (postTime / 1000 >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 YEAR)) AND (appName LIKE 'Abendschau') ORDER BY `number` DESC LIMIT 10";
// ALL TIME
$query9 = "SELECT appName, COUNT(*) AS number FROM Notification WHERE appName LIKE 'SWR Aktuell'
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Inforadio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'rbb|24')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Brandenburg Aktuell')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Radio Paloma')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Radio SAW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'hr-INFO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SWR3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Fritz')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'YOU FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'hr2-kultur')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'hr3')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'boerse.ARD')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Kulturradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'radioeins')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'DASDING')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'KaffeeOderTee')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SWR4 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SWR4 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'ARDBuffet')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SWR1 RP')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SWR1 BW')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'ROCKLAND.fm')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE '1A Webradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Hit Radio N1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Charivari 98.6')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Radio F 94.5')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Pirate Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Gong 97.1')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Radio TEDDY')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'WIGLmania')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'BB RADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Kochblogradio')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Radio Gong')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SCHWARZWALDRADIO')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Retro FM')
UNION ALL SELECT appName, COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Abendschau') ORDER BY `number` DESC LIMIT 10";
$query10 = "SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SWR Aktuell')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Inforadio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'rbb|24')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Brandenburg Aktuell')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Radio Paloma')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Radio SAW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'hr-INFO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SWR3')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Fritz')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'YOU FM')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'hr2-kultur')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'hr3')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'boerse.ARD')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Kulturradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'radioeins')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'DASDING')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'KaffeeOderTee')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SWR4 BW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SWR4 RP')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'ARDBuffet')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SWR1 RP')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SWR1 BW')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'ROCKLAND.fm')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE '1A Webradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Hit Radio N1')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Charivari 98.6')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Radio F 94.5')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Pirate Gong')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Gong 97.1')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Radio TEDDY')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'WIGLmania')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'BB RADIO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Kochblogradio')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Radio Gong')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'SCHWARZWALDRADIO')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Retro FM')
UNION ALL SELECT COUNT(*) AS number FROM Notification WHERE (appName LIKE 'Abendschau') ORDER BY `number` DESC LIMIT 10";

$result1 = mysqli_query($connect, $query1);
$result2 = mysqli_query($connect, $query2);
$result3 = mysqli_query($connect, $query3);
$result4 = mysqli_query($connect, $query4);
$result5 = mysqli_query($connect, $query5);
$result6 = mysqli_query($connect, $query6);
$result7 = mysqli_query($connect, $query7);
$result8 = mysqli_query($connect, $query8);
$result9 = mysqli_query($connect, $query9);
$result10 = mysqli_query($connect, $query10);
?>
